name: Build and Push Docker Image to ECR

on:
  push:
    branches: [ master ]  # ✅ Changed from 'main' to 'master'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to ECR
        run: |
          docker build -t my-app .
          docker tag my-app:latest <your_aws_account_id>.dkr.ecr.ap-south-1.amazonaws.com/my-app:latest
          docker push <331086148814>.dkr.ecr.ap-south-1.amazonaws.com/my-app:latest
